insert into jazyky values(null,'Aj','');
insert into jazyky values(null,'Nj','');
insert into jazyky values(null,'Fr','');
insert into jazyky values(null,'Es','');
insert into jazyky values(null,'It','');
insert into jazyky values(null,'Ru','');

insert into info values('SlovnikLite 1.0',1,1,'2021-06-02',null,'První verze - novı student, testování, vkládání slovíèek, uloené vısledky, uloené testy, nastavení studenta, ukládání testù, vısledkù');

insert into ucebnice values(null,'Happy Street 1',1);

insert into lekce values(null,1,1,'Greeting colors numbers');
insert into lekce values(null,1,2,'At school');
insert into lekce values(null,1,3,'Happy house');
insert into lekce values(null,1,4,'At the shop');
insert into lekce values(null,1,5,'At the park');
insert into lekce values(null,1,6,'Gregs flat');
insert into lekce values(null,1,7,'In the street');
insert into lekce values(null,1,8,'In the playground');
insert into lekce values(null,1,9,'At the sports centre');

insert into slovicka values(null,'Ahoj!','Hello!',1);
insert into slovicka values(null,'Èau!','Hi!',1);
insert into slovicka values(null,'Nashle!','Bye!',1);
insert into slovicka values(null,'Na shledanou!','Goodbey!',1);
insert into slovicka values(null,'Jak se máš?; Jak se máte?','How are you?',1);
insert into slovicka values(null,'Dobøe!','Fine!',1);
insert into slovicka values(null,'jméno','name',1);
insert into slovicka values(null,'vidìt','see',1);
insert into slovicka values(null,'zítra','tomorrow',1);
insert into slovicka values(null,'jedna','one',1);
insert into slovicka values(null,'dvì','two',1);
insert into slovicka values(null,'tøi','three',1);
insert into slovicka values(null,'ètyøi','four',1);
insert into slovicka values(null,'pìt','five',1);
insert into slovicka values(null,'šest','six',1);
insert into slovicka values(null,'sedm','seven',1);
insert into slovicka values(null,'osm','eight',1);
insert into slovicka values(null,'devìt','nine',1);
insert into slovicka values(null,'deset','ten',1);
insert into slovicka values(null,'jedenáct','eleven',1);
insert into slovicka values(null,'dvanáct','twelve',1);
insert into slovicka values(null,'èervená','red',1);
insert into slovicka values(null,'bílá','white',1);
insert into slovicka values(null,'modrá','blue',1);
insert into slovicka values(null,'zelená','green',1);
insert into slovicka values(null,'èerná','black',1);
insert into slovicka values(null,'fialová','purple',1);
insert into slovicka values(null,'rùová','pink',1);
insert into slovicka values(null,'hnìdá','brown',1);

insert into slovicka values(null,'kniha','book',2);
insert into slovicka values(null,'pero','pen',2);
insert into slovicka values(null,'tuka','pencil',2);
insert into slovicka values(null,'penál','pencil case',2);
insert into slovicka values(null,'guma','rubber',2);
insert into slovicka values(null,'pravítko','ruler',2);
insert into slovicka values(null,'lepidlo','glue',2);
insert into slovicka values(null,'nùky','scissors',2);
insert into slovicka values(null,'kalkulaèka','calculator',2);
insert into slovicka values(null,'uèitel;uèitelka','teacher',2);
insert into slovicka values(null,'tøída','classroom',2);
insert into slovicka values(null,'kamarád;kamarádka','friend',2);
insert into slovicka values(null,'pøestávka','playtime',2);
insert into slovicka values(null,'prosím','please',2);
insert into slovicka values(null,'tady, zde','here',2);
insert into slovicka values(null,'dìkuji ti;dìkuji vám','thank you',2);
insert into slovicka values(null,'moci;umìt','can',2);
insert into slovicka values(null,'vypùjèit','borrow',2);
insert into slovicka values(null,'ano','yes',2);
insert into slovicka values(null,'Odkud jsi?','Where are you from?',2);

insert into slovicka values(null,'hraèka','toy',3);
insert into slovicka values(null,'auto','car',3);
insert into slovicka values(null,'vlak','train',3);
insert into slovicka values(null,'panenka','doll',3);
insert into slovicka values(null,'farma','farm',3);
insert into slovicka values(null,'nákladní auto','lorry',3);
insert into slovicka values(null,'robot','robot',3);
insert into slovicka values(null,'pøíšera','monster',3);
insert into slovicka values(null,'raketa','rocket',3);
insert into slovicka values(null,'dinosaurus','dinosaur',3);
insert into slovicka values(null,'osel','donkey',3);
insert into slovicka values(null,'kuelky','skittles',3);
insert into slovicka values(null,'medvídek','teddy bear',3);
insert into slovicka values(null,'bubínek','drum',3);
insert into slovicka values(null,'láhev','bottle',3);
insert into slovicka values(null,'krabice','box',3);
insert into slovicka values(null,'knoflík','button',3);
insert into slovicka values(null,'z','from',3);
insert into slovicka values(null,'ne','no',3);
insert into slovicka values(null,'plast;plastovı','plastic',3);
insert into slovicka values(null,'karton;kartonovı','carboard',3);
insert into slovicka values(null,'ponoky','sock',3);
insert into slovicka values(null,'tuba','tube',3);
insert into slovicka values(null,'tvùj;váš','your',3);
insert into slovicka values(null,'oblíbenı','favourite',3);

insert into slovicka values(null,'jablko','apple',4);
insert into slovicka values(null,'banán','banana',4);
insert into slovicka values(null,'pomeranè','orange',4);
insert into slovicka values(null,'hruška','pear',4);
insert into slovicka values(null,'dort','cake',4);
insert into slovicka values(null,'zmrzlina','ice cream',4);
insert into slovicka values(null,'sešenky','biscuits',4);
insert into slovicka values(null,'brokolice','brocolli',4);
insert into slovicka values(null,'tìstoviny','pasta',4);
insert into slovicka values(null,'pomeranè','orange',4);
insert into slovicka values(null,'hruška','pear',4);
insert into slovicka values(null,'èokoláda','chocolate',4);
insert into slovicka values(null,'vìdìt','know',4);
insert into slovicka values(null,'sedìt','sit',4);
insert into slovicka values(null,'dolù','down',4);
insert into slovicka values(null,'stát','stand',4);
insert into slovicka values(null,'nahoru','up',4);
insert into slovicka values(null,'dotknout se','rouch',4);
insert into slovicka values(null,'toèit;toèit se;otoèit;otoèit se','turn',4);

insert into slovicka values(null,'míè','ball',5);
insert into slovicka values(null,'kolo','bike',5);
insert into slovicka values(null,'loï','boat',5);
insert into slovicka values(null,'papírovı drak','kite',5);
insert into slovicka values(null,'fotbal','football',5);
insert into slovicka values(null,'letadlo','plane',5);
insert into slovicka values(null,'závodní auto','racing car',5);
insert into slovicka values(null,'velkı','big',5);
insert into slovicka values(null,'malı','small',5);
insert into slovicka values(null,'pøejít; pøejít silnici','cross',5);
insert into slovicka values(null,'Nebìhej!',"Don't run!",5);
insert into slovicka values(null,'poslouchat','listen',5);
insert into slovicka values(null,'Zastav se!','Stop!',5);
insert into slovicka values(null,'jedenáct','eleven',5);
insert into slovicka values(null,'dvanáct','twelve',5);
insert into slovicka values(null,'tøináct','thirteen',5);
insert into slovicka values(null,'ètrnáct','fourteen',5);
insert into slovicka values(null,'patnáct','fifteen',5);
insert into slovicka values(null,'šestnáct','sixteen',5);
insert into slovicka values(null,'sedmnáct','seventenn',5);
insert into slovicka values(null,'osmnáct','eighteen',5);
insert into slovicka values(null,'devetenáct','nineteen',5);
insert into slovicka values(null,'dvacet','twenty',5);

insert into slovicka values(null,'postel','bed',6);
insert into slovicka values(null,'idle','chair',6);
insert into slovicka values(null,'stùl','table',6);
insert into slovicka values(null,'šatní skøíò','wardrobe',6);
insert into slovicka values(null,'skøíò','cupboard',6);
insert into slovicka values(null,'knihovna','bookcase',6);
insert into slovicka values(null,'køeèek','hamster',6);
insert into slovicka values(null,'poèítaè','computer',6);
insert into slovicka values(null,'lonice','bedroom',6);
insert into slovicka values(null,'koupelna','bathroom',6);
insert into slovicka values(null,'kuchynì','kitchen',6);
insert into slovicka values(null,'obıvací pokoj','sittingromm',6);
insert into slovicka values(null,'kytara','guitar',6);
insert into slovicka values(null,'obraz','painting',6);
insert into slovicka values(null,'rádio','radio',6);
insert into slovicka values(null,'kobereèek','rug',6);
insert into slovicka values(null,'pohovka','sofa',6);
insert into slovicka values(null,'krb','fireplace',6);
insert into slovicka values(null,'pod','under',6);
insert into slovicka values(null,'v','in',6);
insert into slovicka values(null,'na','on',6);
insert into slovicka values(null,'budík','alarm clock',6);
insert into slovicka values(null,'lampa','lamp',6);
insert into slovicka values(null,'plakát','poster',6);

insert into slovicka values(null,'dìátko','baby',7);
insert into slovicka values(null,'chlapec;kluk','boy',7);
insert into slovicka values(null,'dívka;holka','girl',7);
insert into slovicka values(null,'mu','man',7);
insert into slovicka values(null,'ena','woman',7);
insert into slovicka values(null,'pes','dog',7);
insert into slovicka values(null,'mìsto','town',7);
insert into slovicka values(null,'pekaøství',"baker's",7);
insert into slovicka values(null,'autobusová zastávka','bus stop',7);
insert into slovicka values(null,'kavárna','café',7);
insert into slovicka values(null,'poštovní schránka','post box',7);
insert into slovicka values(null,'nejlepší','best',7);
insert into slovicka values(null,'blonïatı','blond',7);
insert into slovicka values(null,'oèi','eyes',7);
insert into slovicka values(null,'tlustı','fat',7);
insert into slovicka values(null,'vlasy','hair',7);
insert into slovicka values(null,'dlouhı','long',7);
insert into slovicka values(null,'starı','old',7);
insert into slovicka values(null,'vysokı','tall',7);
insert into slovicka values(null,'hubenı','thin',7);
insert into slovicka values(null,'mladı','young',7);
insert into slovicka values(null,'brıle','glasses',7);

insert into slovicka values(null,'boty;vysoké boty','boots',8);
insert into slovicka values(null,'èepice s kšiltem','cap',8);
insert into slovicka values(null,'èepice;klobouk;pøilba','hat',8);
insert into slovicka values(null,'svetøík','jumper',8);
insert into slovicka values(null,'bota','shoe',8);
insert into slovicka values(null,'suknì','skirt',8);
insert into slovicka values(null,'krátkı','short',8);
insert into slovicka values(null,'ponoka','sock',8);
insert into slovicka values(null,'trièko','t-shirt',8);
insert into slovicka values(null,'uniforma','uniform',8);
insert into slovicka values(null,'mikina','sweatshirt',8);
insert into slovicka values(null,'kalhoty','trousers',8);
insert into slovicka values(null,'odznak','badge',8);
insert into slovicka values(null,'odhadnout','guess',8);
insert into slovicka values(null,'mapa','map',8);
insert into slovicka values(null,'mìøit','measure',8);
insert into slovicka values(null,'skluzavka','slide',8);
insert into slovicka values(null,'pøíliš','too',8);
insert into slovicka values(null,'hasiè','firefighter',8);
insert into slovicka values(null,'maškarní kostım','fancy dress',8);

insert into slovicka values(null,'pae','arm',9);
insert into slovicka values(null,'tìlo','body',9);
insert into slovicka values(null,'chodidlo','foot',9);
insert into slovicka values(null,'chodidla','feet',9);
insert into slovicka values(null,'boky','hips',9);
insert into slovicka values(null,'noha','leg',9);
insert into slovicka values(null,'hlava','head',9);
insert into slovicka values(null,'ruka','hand',9);
insert into slovicka values(null,'ohnout','bend',9);
insert into slovicka values(null,'potápìt se','dive',9);
insert into slovicka values(null,'utéct','escape',9);
insert into slovicka values(null,'slyšet','hear',9);
insert into slovicka values(null,'skákat','jump',9);
insert into slovicka values(null,'kopnout;vykopnout','kick',9);
insert into slovicka values(null,'lyovat','sky',9);
insert into slovicka values(null,'spát','sleep',9);
insert into slovicka values(null,'plavat','swim',9);
insert into slovicka values(null,'cvik;cvièení','exercise',9);
insert into slovicka values(null,'odvánı','bolrd',9);
insert into slovicka values(null,'stateènı','brave',9);
insert into slovicka values(null,'ovoce','fruit',9);
insert into slovicka values(null,'zdravı','healthy',9);
insert into slovicka values(null,'levı','left',9);
insert into slovicka values(null,'pravı','right',9);
insert into slovicka values(null,'voda','water',9);
insert into slovicka values(null,'tenis','tennis',9);





